# Generated by Django 5.2 on 2025-04-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('lesson_name', models.CharField(max_length=30)),
                ('last_lesson', models.DateField()),
                ('years_of_teaching', models.IntegerField()),
                ('is_working', models.BooleanField(default=True)),
            ],
        ),
    ]
